packages:
  - playground
  - docs

catalog:
  '@types/node': ^24.10.1
  '@unocss/core': 66.5.9
  '@unocss/preset-icons': 66.5.9
  '@unocss/preset-mini': 66.5.9
  '@unocss/preset-typography': 66.5.9
  '@unocss/preset-web-fonts': 66.5.9
  '@unocss/preset-wind4': 66.5.9
  '@unocss/transformer-directives': 66.5.9
  '@unocss/transformer-variant-group': 66.5.9
  '@vinicunca/eslint-config': 3.29.0
  '@vinicunca/perkakas': ^1.9.0
  '@vitejs/plugin-vue': ^6.0.2
  bumpp: ^10.3.1
  defu: ^6.1.4
  eslint: ^9.39.1
  lint-staged: ^16.2.7
  magic-string: ^0.30.21
  postcss: ^8.5.6
  postcss-js: ^5.0.1
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  taze: ^19.9.0
  tsdown: ^0.16.6
  typescript: ^5.9.3
  unocss: 66.5.9
  vite: ^7.2.4
  vitest: ^4.0.13
  vue: ^3.5.24
  vue-tsc: ^3.1.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
