packages:
  - playground
  - docs
  - packages/**

catalog:
  '@iconify/json': ^2.2.396
  '@types/node': ^24.8.0
  '@unocss/core': 66.5.4
  '@unocss/preset-icons': 66.5.4
  '@unocss/preset-mini': 66.5.4
  '@unocss/preset-typography': 66.5.4
  '@unocss/preset-web-fonts': 66.5.4
  '@unocss/preset-wind4': 66.5.4
  '@unocss/transformer-directives': 66.5.4
  '@unocss/transformer-variant-group': 66.5.4
  '@vinicunca/eslint-config': 3.29.0
  '@vinicunca/perkakas': ^1.8.0
  '@vitejs/plugin-vue': ^6.0.1
  akar: ^1.11.0
  bumpp: ^10.3.1
  defu: ^6.1.4
  eslint: ^9.37.0
  lint-staged: ^16.2.4
  magic-string: ^0.30.19
  postcss: ^8.5.6
  postcss-js: ^5.0.1
  postcss-nested: ^7.0.2
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  taze: ^19.8.0
  tsdown: ^0.15.7
  typescript: ^5.9.3
  unocss: 66.5.4
  unplugin-vue-components: ^29.1.0
  vite: ^7.1.10
  vitepress: ^1.6.4
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-tsc: ^3.1.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
