catalog:
  '@iconify/json': ^2.2.279
  '@types/node': ^22.10.1
  '@unocss/core': ^0.65.1
  '@unocss/preset-icons': ^0.65.1
  '@unocss/preset-mini': ^0.65.1
  '@unocss/preset-typography': ^0.65.1
  '@unocss/preset-uno': ^0.65.1
  '@unocss/preset-web-fonts': ^0.65.1
  '@unocss/transformer-directives': ^0.65.1
  '@unocss/transformer-variant-group': ^0.65.1
  '@vinicunca/eslint-config': ^2.15.1
  '@vinicunca/perkakas': ^1.1.0
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^9.8.1
  eslint: ^9.16.0
  lint-staged: ^15.2.10
  postcss: ^8.4.49
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  radix-vue: ^1.9.10
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  typescript: 5.7.2
  unbuild: ^3.0.0-rc.11
  unocss: ^0.65.1
  unplugin-vue-components: ^0.27.5
  vite: ^6.0.3
  vitepress: ^1.5.0
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-tsc: ^2.1.10
packages:
  - playground
  - docs
  - packages/**
