packages:
  - playground
  - docs
  - packages/**

catalog:
  '@iconify/json': ^2.2.371
  '@types/node': ^24.2.1
  '@unocss/core': ^66.4.2
  '@unocss/preset-icons': ^66.4.2
  '@unocss/preset-mini': ^66.4.2
  '@unocss/preset-typography': ^66.4.2
  '@unocss/preset-web-fonts': ^66.4.2
  '@unocss/preset-wind4': ^66.4.2
  '@unocss/transformer-directives': ^66.4.2
  '@unocss/transformer-variant-group': ^66.4.2
  '@vinicunca/eslint-config': ^3.21.1
  '@vinicunca/perkakas': ^1.7.1
  '@vitejs/plugin-vue': ^6.0.1
  bumpp: ^10.2.2
  defu: ^6.1.4
  eslint: ^9.33.0
  lint-staged: ^16.1.5
  magic-string: ^0.30.17
  postcss: ^8.5.6
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  prettier: ^3.6.2
  radix-vue: ^1.9.17
  simple-git-hooks: ^2.13.1
  taze: ^19.1.0
  typescript: ^5.9.2
  unbuild: ^3.6.0
  unocss: ^66.4.2
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.1
  vitepress: ^1.6.4
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-tsc: ^3.0.5

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
