packages:
  - playground
  - docs
  - packages/**
catalog:
  '@iconify/json': ^2.2.359
  '@types/node': ^22.16.4
  '@unocss/core': ^66.3.3
  '@unocss/preset-icons': ^66.3.3
  '@unocss/preset-mini': ^66.3.3
  '@unocss/preset-typography': ^66.3.3
  '@unocss/preset-web-fonts': ^66.3.3
  '@unocss/transformer-directives': ^66.3.3
  '@unocss/transformer-variant-group': ^66.3.3
  '@vinicunca/eslint-config': ^3.18.0
  '@vinicunca/perkakas': ^1.6.0
  '@vitejs/plugin-vue': ^6.0.0
  bumpp: ^10.2.0
  defu: ^6.1.4
  eslint: ^9.31.0
  lint-staged: ^16.1.2
  magic-string: ^0.30.17
  postcss: ^8.5.6
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  prettier: ^3.6.2
  radix-vue: ^1.9.17
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.3
  unplugin-vue-components: ^28.8.0
  vite: ^7.0.4
  vitepress: ^1.6.3
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-tsc: ^3.0.1
