packages:
  - playground
  - docs
  - packages/**
catalog:
  '@iconify/json': ^2.2.317
  '@types/node': ^22.13.10
  '@unocss/core': ^66.0.0
  '@unocss/preset-icons': ^66.0.0
  '@unocss/preset-mini': ^66.0.0
  '@unocss/preset-typography': ^66.0.0
  '@unocss/preset-web-fonts': ^66.0.0
  '@unocss/preset-wind3': ^66.0.0
  '@unocss/transformer-directives': ^66.0.0
  '@unocss/transformer-variant-group': ^66.0.0
  '@vinicunca/eslint-config': ^3.8.0
  '@vinicunca/perkakas': ^1.4.0
  '@vitejs/plugin-vue': ^5.2.2
  bumpp: ^10.1.0
  eslint: ^9.22.0
  lint-staged: ^15.5.0
  magic-string: ^0.30.17
  postcss: ^8.5.3
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  radix-vue: ^1.9.17
  simple-git-hooks: ^2.11.1
  taze: ^19.0.2
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.1
  vite: ^6.2.2
  vitepress: ^1.6.3
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-tsc: ^2.2.8
