packages:
  - playground
  - docs
  - packages/**
catalog:
  '@iconify/json': ^2.2.346
  '@types/node': ^22.15.30
  '@unocss/core': 66.1.3
  '@unocss/preset-icons': 66.1.3
  '@unocss/preset-mini': 66.1.3
  '@unocss/preset-typography': 66.1.3
  '@unocss/preset-web-fonts': 66.1.3
  '@unocss/transformer-directives': 66.1.3
  '@unocss/transformer-variant-group': 66.1.3
  '@vinicunca/eslint-config': ^3.16.1
  '@vinicunca/perkakas': ^1.6.0
  '@vitejs/plugin-vue': ^5.2.4
  bumpp: ^10.1.1
  defu: ^6.1.4
  eslint: ^9.28.0
  lint-staged: ^16.1.0
  magic-string: ^0.30.17
  postcss: ^8.5.4
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  prettier: ^3.5.3
  radix-vue: ^1.9.17
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: 66.1.3
  unplugin-vue-components: ^28.7.0
  vite: ^6.3.5
  vitepress: ^1.6.3
  vitest: ^3.2.2
  vue: ^3.5.16
  vue-tsc: ^2.2.10
