shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs

catalog:
  '@types/node': ^24.10.8
  '@unocss/core': 66.6.1
  '@unocss/preset-icons': 66.6.1
  '@unocss/preset-mini': 66.6.1
  '@unocss/preset-typography': 66.6.1
  '@unocss/preset-web-fonts': 66.6.1
  '@unocss/preset-wind4': 66.6.1
  '@unocss/transformer-directives': 66.6.1
  '@unocss/transformer-variant-group': 66.6.1
  '@vinicunca/eslint-config': 4.8.0
  '@vinicunca/perkakas': ^1.13.2
  '@vitejs/plugin-vue': ^6.0.3
  bumpp: ^10.4.1
  culori: ^4.0.2
  defu: ^6.1.4
  eslint: ^10.0.2
  lint-staged: ^16.2.7
  magic-string: ^0.30.21
  postcss: ^8.5.6
  postcss-js: ^5.0.3
  prettier: ^3.8.0
  simple-git-hooks: ^2.13.1
  tsdown: ^0.18.4
  typescript: ^5.9.3
  unocss: 66.6.1
  vite: ^7.3.1
  vitest: ^4.0.17
  vue: ^3.5.26
  vue-tsc: ^3.2.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
