catalog:
  '@iconify/json': ^2.2.309
  '@types/node': ^22.13.4
  '@unocss/core': ^66.0.0
  '@unocss/preset-icons': ^66.0.0
  '@unocss/preset-mini': ^66.0.0
  '@unocss/preset-typography': ^66.0.0
  '@unocss/preset-web-fonts': ^66.0.0
  '@unocss/preset-wind3': ^66.0.0
  '@unocss/transformer-directives': ^66.0.0
  '@unocss/transformer-variant-group': ^66.0.0
  '@vinicunca/eslint-config': ^3.4.0
  '@vinicunca/perkakas': ^1.3.0
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^10.0.3
  eslint: ^9.20.1
  lint-staged: ^15.4.3
  postcss: ^8.5.3
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  radix-vue: ^1.9.16
  simple-git-hooks: ^2.11.1
  taze: ^18.6.0
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.0
  vite: ^6.1.1
  vitepress: ^1.6.3
  vitest: ^3.0.6
  vue: ^3.5.13
  vue-tsc: ^2.2.2
packages:
  - playground
  - docs
  - packages/**
