shellEmulator: true

packages:
  - playground
  - docs

catalog:
  '@types/node': ^24.12.4
  '@unocss/preset-icons': 66.7.0
  '@unocss/preset-mini': 66.7.0
  '@unocss/preset-typography': 66.7.0
  '@unocss/preset-web-fonts': 66.7.0
  '@unocss/preset-wind4': 66.7.0
  '@unocss/transformer-directives': 66.7.0
  '@unocss/transformer-variant-group': 66.7.0
  '@vinicunca/eslint-config': 5.2.0
  '@vinicunca/perkakas': ^1.15.0
  '@vitejs/plugin-vue': ^6.0.7
  bumpp: ^11.1.0
  culori: ^4.0.2
  defu: ^6.1.7
  eslint: ^10.4.0
  lint-staged: ^16.4.0
  magic-string: ^0.30.21
  postcss: ^8.5.15
  postcss-js: ^5.1.0
  prettier: ^3.8.3
  simple-git-hooks: ^2.13.1
  tsdown: ^0.22.1
  typescript: ^6.0.3
  unocss: 66.7.0
  vite: ^7.3.3
  vitest: ^4.1.7
  vue: ^3.5.35
  vue-tsc: ^3.3.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
