catalog:
  '@iconify/json': ^2.2.299
  '@types/node': ^22.10.10
  '@unocss/core': ^65.4.3
  '@unocss/preset-icons': ^65.4.3
  '@unocss/preset-mini': ^65.4.3
  '@unocss/preset-typography': ^65.4.3
  '@unocss/preset-uno': ^65.4.3
  '@unocss/preset-web-fonts': ^65.4.3
  '@unocss/transformer-directives': ^65.4.3
  '@unocss/transformer-variant-group': ^65.4.3
  '@vinicunca/eslint-config': ^2.15.7
  '@vinicunca/perkakas': ^1.2.3
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^9.10.2
  eslint: ^9.18.0
  lint-staged: ^15.4.2
  postcss: ^8.5.1
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  radix-vue: ^1.9.12
  simple-git-hooks: ^2.11.1
  taze: ^18.3.0
  typescript: 5.7.2
  unbuild: ^3.3.1
  unocss: ^65.4.3
  unplugin-vue-components: ^28.0.0
  vite: ^6.0.11
  vitepress: ^1.6.3
  vitest: ^3.0.4
  vue: ^3.5.13
  vue-tsc: ^2.2.0
packages:
  - playground
  - docs
  - packages/**
