catalog:
  '@iconify/json': ^2.2.278
  '@types/node': ^22.10.1
  '@unocss/core': ^0.65.0
  '@unocss/preset-attributify': ^0.65.0
  '@unocss/preset-icons': ^0.65.0
  '@unocss/preset-mini': ^0.65.0
  '@unocss/preset-typography': ^0.65.0
  '@unocss/preset-uno': ^0.65.0
  '@unocss/preset-web-fonts': ^0.64.1
  '@unocss/transformer-directives': ^0.65.0
  '@unocss/transformer-variant-group': ^0.65.0
  '@vinicunca/eslint-config': ^2.15.1
  '@vinicunca/perkakas': ^1.1.0
  '@vitejs/plugin-vue': ^5.0.5
  bumpp: ^9.8.1
  eslint: ^9.16.0
  lint-staged: ^15.2.10
  postcss: ^8.4.49
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  radix-vue: ^1.9.10
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  typescript: 5.7.2
  unbuild: ^3.0.0-rc.11
  unocss: ^0.65.0
  unplugin-vue-components: ^0.27.5
  vite: ^5.2.13
  vitepress: ^1.5.0
  vitest: ^2.1.8
  vue: ^3.4.27
  vue-tsc: ^2.0.21
packages:
  - playground
  - docs
  - packages/**
