packages:
  - playground
  - docs
  - packages/**

catalog:
  '@iconify/json': ^2.2.382
  '@types/node': ^24.3.1
  '@unocss/core': 66.5.1
  '@unocss/preset-icons': 66.5.1
  '@unocss/preset-mini': 66.5.1
  '@unocss/preset-typography': 66.5.1
  '@unocss/preset-web-fonts': 66.5.1
  '@unocss/preset-wind4': 66.5.1
  '@unocss/transformer-directives': 66.5.1
  '@unocss/transformer-variant-group': 66.5.1
  '@vinicunca/eslint-config': ^3.24.0
  '@vinicunca/perkakas': ^1.7.1
  '@vitejs/plugin-vue': ^6.0.1
  akar: ^1.11.0
  bumpp: ^10.2.3
  defu: ^6.1.4
  eslint: ^9.35.0
  lint-staged: ^16.1.6
  magic-string: ^0.30.19
  postcss: ^8.5.6
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  taze: ^19.6.0
  tsdown: ^0.14.2
  typescript: ^5.9.2
  unocss: 66.5.1
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.5
  vitepress: ^1.6.4
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-tsc: ^3.0.6

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
