packages:
  - playground
  - docs
  - packages/**

catalog:
  '@iconify/json': ^2.2.393
  '@types/node': ^24.7.0
  '@unocss/core': 66.5.2
  '@unocss/preset-icons': 66.5.2
  '@unocss/preset-mini': 66.5.2
  '@unocss/preset-typography': 66.5.2
  '@unocss/preset-web-fonts': 66.5.2
  '@unocss/preset-wind4': 66.5.2
  '@unocss/transformer-directives': 66.5.2
  '@unocss/transformer-variant-group': 66.5.2
  '@vinicunca/eslint-config': ^3.27.0
  '@vinicunca/perkakas': ^1.7.1
  '@vitejs/plugin-vue': ^6.0.1
  akar: ^1.11.0
  bumpp: ^10.3.1
  defu: ^6.1.4
  eslint: ^9.37.0
  lint-staged: ^16.2.3
  magic-string: ^0.30.19
  postcss: ^8.5.6
  postcss-js: ^5.0.1
  postcss-nested: ^7.0.2
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  taze: ^19.7.0
  tsdown: ^0.15.6
  typescript: ^5.9.3
  unocss: 66.5.2
  unplugin-vue-components: ^29.1.0
  vite: ^7.1.9
  vitepress: ^1.6.4
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-tsc: ^3.1.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
