catalog:
  '@iconify/json': ^2.2.307
  '@types/node': ^22.13.4
  '@unocss/core': ^65.5.0
  '@unocss/preset-icons': ^65.5.0
  '@unocss/preset-mini': ^65.5.0
  '@unocss/preset-typography': ^65.5.0
  '@unocss/preset-uno': ^65.5.0
  '@unocss/preset-web-fonts': ^65.5.0
  '@unocss/transformer-directives': ^65.5.0
  '@unocss/transformer-variant-group': ^65.5.0
  '@vinicunca/eslint-config': ^3.1.1
  '@vinicunca/perkakas': ^1.2.3
  '@vitejs/plugin-vue': ^5.2.1
  bumpp: ^10.0.3
  eslint: ^9.20.1
  lint-staged: ^15.4.3
  postcss: ^8.5.2
  postcss-js: ^4.0.1
  postcss-nested: ^7.0.2
  radix-vue: ^1.9.14
  simple-git-hooks: ^2.11.1
  taze: ^18.5.0
  typescript: 5.7.2
  unbuild: ^3.3.1
  unocss: ^65.5.0
  unplugin-vue-components: ^28.1.0
  vite: ^6.1.0
  vitepress: ^1.6.3
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-tsc: ^2.2.2
packages:
  - playground
  - docs
  - packages/**
