export const FLUID_UTILITIES = {
  'fluid-text': 'font-size',
  'fluid-w': 'width',
  'fluid-min-w': 'min-width',
  'fluid-max-w': 'max-width',
  'fluid-h': 'height',
  'fluid-min-h': 'min-height',
  'fluid-max-h': 'max-height',
  'fluid-p': 'padding',
  'fluid-pt': 'padding-top',
  'fluid-pb': 'padding-bottom',
  'fluid-pl': 'padding-left',
  'fluid-pr': 'padding-right',
  'fluid-px': ['padding-left', 'padding-right'],
  'fluid-py': ['padding-top', 'padding-bottom'],
  'fluid-m': 'margin',
  'fluid-mt': 'margin-top',
  'fluid-mb': 'margin-bottom',
  'fluid-ml': 'margin-left',
  'fluid-mr': 'margin-right',
  'fluid-mx': ['margin-left', 'margin-right'],
  'fluid-my': ['margin-top', 'margin-bottom'],
  'fluid-gap': 'gap',
  'fluid-gap-x': 'column-gap',
  'fluid-gap-y': 'row-gap',
  'fluid-indent': 'text-indent',
  'fluid-scroll-m': 'scroll-margin',
  'fluid-scroll-mt': 'scroll-margin-top',
  'fluid-scroll-mb': 'scroll-margin-bottom',
  'fluid-scroll-ml': 'scroll-margin-left',
  'fluid-scroll-mr': 'scroll-margin-right',
  'fluid-scroll-mx': ['scroll-margin-left', 'scroll-margin-right'],
  'fluid-scroll-my': ['scroll-margin-top', 'scroll-margin-bottom'],
  'fluid-scroll-ms': 'scroll-margin-inline-start',
  'fluid-scroll-me': 'scroll-margin-inline-end',
  'fluid-scroll-p': 'scroll-padding',
  'fluid-scroll-pt': 'scroll-padding-top',
  'fluid-scroll-pb': 'scroll-padding-bottom',
  'fluid-scroll-pl': 'scroll-padding-left',
  'fluid-scroll-pr': 'scroll-padding-right',
  'fluid-scroll-px': ['scroll-padding-left', 'scroll-padding-right'],
  'fluid-scroll-py': ['scroll-padding-top', 'scroll-padding-bottom'],
  'fluid-scroll-ps': 'scroll-padding-inline-start',
  'fluid-scroll-pe': 'scroll-padding-inline-end',
  'fluid-leading': 'line-height',
  'fluid-top': 'top',
  'fluid-right': 'right',
  'fluid-bottom': 'bottom',
  'fluid-left': 'left',
  'fluid-inset': 'inset',
  'fluid-inset-x': ['left', 'right'],
  'fluid-inset-y': ['top', 'bottom'],
};
