/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FluidContainer: typeof import('./.vitepress/components/fluid-container.vue')['default']
    FluidGap: typeof import('./.vitepress/components/fluid-gap.vue')['default']
    FluidMargin: typeof import('./.vitepress/components/fluid-margin.vue')['default']
    FluidNegativePositive: typeof import('./.vitepress/components/fluid-negative-positive.vue')['default']
    FluidPadding: typeof import('./.vitepress/components/fluid-padding.vue')['default']
    FluidRanges: typeof import('./.vitepress/components/fluid-ranges.vue')['default']
    FluidTypography: typeof import('./.vitepress/components/fluid-typography.vue')['default']
    FluidWidthHeight: typeof import('./.vitepress/components/fluid-width-height.vue')['default']
    PresetAnimation: typeof import('./.vitepress/components/preset-animation.vue')['default']
  }
}
